"""Добавлено поле для сохранения файла, и айди фото опциональное

Revision ID: c111a6351970
Revises: 55633d65ff56
Create Date: 2026-06-15 17:51:34.306477

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c111a6351970'
down_revision: Union[str, Sequence[str], None] = '55633d65ff56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_tg_id', sa.String(), nullable=False, server_default=''))
    op.alter_column('products', 'photo_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'photo_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'product_tg_id')
    # ### end Alembic commands ###
